### PR TITLE
make run script not assume the current directory is in the path

### PR DESCRIPTION
**Pull request by bmaddy**

### CODE REVIEW

**Comment by grzm** [comment]
Thanks for looking at this. Would you clarify the intent of this for me? The assumption isn't that the `halite` binary is in a certain location (in the current directory): it's that it's in the path. For example, in the collab environment last night, the `halite` binary was located in `~/bin/`, and `~/bin/` was in the path. Prior to the event, I ran `script/init`. I suppose I could make this more explicit in the README: it's currently buried in the Notes section at the bottom.

**Comment by bmaddy** [comment]
Ah, my bad. Someone told me the other night that you need `halite` in your project's root directory. Looks like I didn't set things up correctly. I'll try running that init and see if things work out.

**Comment by bmaddy** [comment]
Ah, it turns out the starter kits that you download from the website is different for each os. The MacOS version doesn't have a script directory and has `run_game.sh` in the root directory and there's no installer helper. I guess I'm going to have to go figure out how to set this thing up. :/

**Comment by grzm** [comment]
This isn't a straight checkout of the Clojure starter kit. I added the additional scripts and moved `run_game.sh` into the script directory to make it more convenient for the event.

You can grab the Mac OS version of the halite binary and put that in your path. Ignore the `init` script and sourcing `config.env`. If you want to upload from the command line, install the hlt client tools via `pip` (`pip3`)  and run `htl auth` to se the API key. The `package` and `upload` scripts should work as-is. I've been using the process locally on my Mac. If I've forgotten something, or you've got further questions, feel free to email me, or perhaps hit me up on Clojurian's slack.

**Pull request closed without merging**
